#!/usr/bin/env bash
#
# Regenerates checksums.txt for the versions pinned in versions.env.
#
# Run this after bumping a version, and commit the result alongside it:
#
#     pixi run task pin:tools
#
# Neither tool needs its binaries downloaded to be re-pinned — k3d publishes a
# single checksums.txt per release and kubectl publishes a .sha256 per os/arch,
# so this is a handful of small HTTP requests rather than ~250MB of downloads.
#
# Why the digests are stored in-tree rather than fetched at install time:
# verifying a download against a checksum fetched at the same moment only
# proves the transport was intact. A digest recorded here when we reviewed the
# release is an independent anchor — if upstream is ever compromised and
# republishes a binary with a matching checksum, the mismatch surfaces here in
# a diff instead of being installed silently.

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=versions.env
. "${SCRIPT_DIR}/versions.env"

OUT="${SCRIPT_DIR}/checksums.txt"

# The platforms this workspace supports, as os/arch pairs. Mirrors the
# `platforms` list in pixi.toml (linux-64, linux-aarch64, osx-arm64).
PLATFORMS="darwin/arm64 linux/amd64 linux/arm64"

fetch() {
  curl --proto '=https' --tlsv1.2 --fail --show-error -sL "$@"
}

tmp="$(mktemp -d -t freelunch-pin-XXXXXX)"
trap 'rm -rf "${tmp}"' EXIT

{
  echo "# Generated by pin-tools.sh — do not edit by hand."
  echo "# Regenerate with: pixi run task pin:tools"
  echo "#"
  echo "# tool version os arch sha256"
} >"${tmp}/out"

# --- k3d: one checksums.txt for the whole release ---------------------------
echo "fetching k3d ${K3D_VERSION} checksums"
fetch "https://github.com/k3d-io/k3d/releases/download/${K3D_VERSION}/checksums.txt" \
  -o "${tmp}/k3d.txt"

for platform in ${PLATFORMS}; do
  os="${platform%%/*}"
  arch="${platform##*/}"
  # Upstream lines look like: <sha256>  _dist/k3d-darwin-arm64
  sum="$(awk -v want="_dist/k3d-${os}-${arch}" '$2 == want {print $1}' "${tmp}/k3d.txt")"
  if [ -z "${sum}" ]; then
    echo "error: no k3d checksum published for ${os}/${arch} at ${K3D_VERSION}" >&2
    exit 1
  fi
  echo "k3d ${K3D_VERSION} ${os} ${arch} ${sum}" >>"${tmp}/out"
done

# --- kubectl: one .sha256 per os/arch ---------------------------------------
for platform in ${PLATFORMS}; do
  os="${platform%%/*}"
  arch="${platform##*/}"
  echo "fetching kubectl ${KUBECTL_VERSION} checksum for ${os}/${arch}"
  sum="$(fetch "https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/${os}/${arch}/kubectl.sha256" |
    tr -d '[:space:]')"
  if [ -z "${sum}" ]; then
    echo "error: no kubectl checksum published for ${os}/${arch} at ${KUBECTL_VERSION}" >&2
    exit 1
  fi
  echo "kubectl ${KUBECTL_VERSION} ${os} ${arch} ${sum}" >>"${tmp}/out"
done

mv "${tmp}/out" "${OUT}"
echo "wrote ${OUT}"
